version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
    - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
    - ./src:/var/www/html/wp-content/plugins/eagle-storytelling-application

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}